# Generated by Django 4.2.13 on 2024-05-13 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Average',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='اسم المقوت')),
            ],
            options={
                'verbose_name': 'مقوت',
                'verbose_name_plural': 'المقاوته',
            },
        ),
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='اسم الصندوق')),
            ],
            options={
                'verbose_name': 'Box',
                'verbose_name_plural': 'Boxs',
            },
        ),
        migrations.CreateModel(
            name='CommunicationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نوع الإتصالات')),
            ],
            options={
                'verbose_name': 'نوع اتصال',
                'verbose_name_plural': 'انواع الإتصالات',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='اسم الشركة')),
            ],
            options={
                'verbose_name': 'شركة',
                'verbose_name_plural': 'الشركات',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='اسم الصنف')),
            ],
            options={
                'verbose_name': 'صنف',
                'verbose_name_plural': 'الأصناف',
            },
        ),
        migrations.CreateModel(
            name='MedicineType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نوع الدواء')),
            ],
            options={
                'verbose_name': 'نوع دواء',
                'verbose_name_plural': 'أنوا الأدوية',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='اسم المحافظة')),
            ],
            options={
                'verbose_name': 'محافظة',
                'verbose_name_plural': 'المحافظات',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SickType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نوع الإصابة')),
            ],
            options={
                'verbose_name': 'نوع إصابة',
                'verbose_name_plural': 'أنواع الإصابات',
            },
        ),
        migrations.CreateModel(
            name='Side',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='اسم الجهة')),
            ],
            options={
                'verbose_name': 'Side',
                'verbose_name_plural': 'Sides',
            },
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='اسم المنطقة')),
            ],
            options={
                'verbose_name': 'بيان',
                'verbose_name_plural': 'البيانات',
            },
        ),
        migrations.CreateModel(
            name='SupportType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نوع السند')),
            ],
            options={
                'verbose_name': 'support_type',
                'verbose_name_plural': 'support_types',
            },
        ),
        migrations.CreateModel(
            name='AssetItem',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.item')),
            ],
            bases=('app.item',),
        ),
        migrations.CreateModel(
            name='CatItem',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.item')),
            ],
            bases=('app.item',),
        ),
        migrations.CreateModel(
            name='ClothItem',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.item')),
            ],
            bases=('app.item',),
        ),
        migrations.CreateModel(
            name='WaterItem',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.item')),
            ],
            bases=('app.item',),
        ),
        migrations.CreateModel(
            name='Sick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='اسم الإصابة')),
                ('sicktype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sicktype', verbose_name='نوع الإصابة')),
            ],
            options={
                'verbose_name': 'إصابة',
                'verbose_name_plural': 'الإصابات',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('amount', models.PositiveBigIntegerField(verbose_name='المبلغ')),
                ('support_number', models.PositiveBigIntegerField(verbose_name='رقم السند')),
                ('support_file', models.FileField(upload_to=None, verbose_name='السند')),
                ('notice', models.TextField(blank=True, null=True, verbose_name='ملاحظة')),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.box', verbose_name='الجهة')),
                ('side', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.side', verbose_name='المستفيد')),
                ('support_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.supporttype', verbose_name='نوع السند')),
            ],
            options={
                'verbose_name': 'صرف',
                'verbose_name_plural': 'الصرف',
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='اسم الدواء')),
                ('medicinetype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.medicinetype', verbose_name='نوع الدواء')),
            ],
            options={
                'verbose_name': 'دواء',
                'verbose_name_plural': 'الأدوية',
            },
        ),
        migrations.CreateModel(
            name='Directorate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='اسم المديرية')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.province', verbose_name='المحافظة')),
            ],
            options={
                'verbose_name': 'مديرية',
                'verbose_name_plural': 'المديريات',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='اسم المنطقة')),
                ('directorate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.directorate', verbose_name='المديرية')),
            ],
            options={
                'verbose_name': 'منطقة',
                'verbose_name_plural': 'الحارات / المناطق',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Water',
            fields=[
                ('order_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.order')),
                ('quantity', models.PositiveIntegerField(verbose_name='الكمية')),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.statement', verbose_name='البيان')),
                ('wateritem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.wateritem', verbose_name='الصنف')),
            ],
            options={
                'verbose_name': 'ماء',
                'verbose_name_plural': 'الماء والثلج',
            },
            bases=('app.order',),
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('order_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.order')),
                ('into', models.CharField(max_length=50, verbose_name='من إلى')),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.statement', verbose_name='البيان')),
            ],
            options={
                'verbose_name': 'مواصلات',
                'verbose_name_plural': 'المواصلات',
            },
            bases=('app.order',),
        ),
        migrations.CreateModel(
            name='MedicineOrder',
            fields=[
                ('order_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.order')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.medicine', verbose_name='الدواء')),
                ('sick', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sick', verbose_name='الإصابة')),
            ],
            options={
                'verbose_name': 'دواء',
                'verbose_name_plural': 'الأدوية',
            },
            bases=('app.order',),
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('order_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.order')),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.statement', verbose_name='البيان')),
            ],
            options={
                'verbose_name': 'تغذية',
                'verbose_name_plural': 'التغذية',
            },
            bases=('app.order',),
        ),
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('order_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.order')),
                ('Communicationtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.communicationtype', verbose_name='نوعه')),
            ],
            options={
                'verbose_name': 'اتصال',
                'verbose_name_plural': 'الاتصالات',
            },
            bases=('app.order',),
        ),
        migrations.CreateModel(
            name='Cloth',
            fields=[
                ('order_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.order')),
                ('clothitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.clothitem', verbose_name='الصنف')),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.statement', verbose_name='البيان')),
            ],
            options={
                'verbose_name': 'ملابس',
                'verbose_name_plural': 'الملبوسات',
            },
            bases=('app.order',),
        ),
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('order_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.order')),
                ('quantity', models.PositiveIntegerField(verbose_name='الكمية')),
                ('average', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.average', verbose_name='المقوت')),
                ('catitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.catitem', verbose_name='نوع القات')),
            ],
            options={
                'verbose_name': 'قات',
                'verbose_name_plural': 'القات',
            },
            bases=('app.order',),
        ),
        migrations.CreateModel(
            name='CashVisit',
            fields=[
                ('order_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.order')),
                ('period', models.PositiveSmallIntegerField(verbose_name='مدة الزيارة')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.area', verbose_name='محل الإقامة')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.medicine', verbose_name='الدواء')),
                ('sick', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sick', verbose_name='الإصابة')),
            ],
            options={
                'verbose_name': 'مزاورات نقدية',
                'verbose_name_plural': 'المزاورات النقدية',
            },
            bases=('app.order',),
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('order_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.order')),
                ('quantity', models.PositiveIntegerField(verbose_name='الكمية')),
                ('serialnumber', models.PositiveBigIntegerField(verbose_name='الرقم التسلسلي')),
                ('detail', models.TextField(verbose_name='المواصفات')),
                ('ward_number', models.PositiveIntegerField(verbose_name='رقم التوريد')),
                ('assetitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.assetitem', verbose_name='اسم الصنف')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.company', verbose_name='الشركة المصنعة')),
            ],
            options={
                'verbose_name': 'اصل',
                'verbose_name_plural': 'الأصول',
            },
            bases=('app.order',),
        ),
    ]
